[package]
name = "https_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
tokio-rustls = "0.23.4"
rustls = "0.20.8"
rustls-native-certs = "0.6.2"
webpki-roots = "0.22.6"
